### ISSUE TITLE
mac osx 10.10 install fails

### ISSUE THREAD

**Issue by michaelaye** [SETI/pds-tools#2]
These are the commands in the make_osx_xxx file:

```bash
PYTHON_INCLUDE=/Users/klay6683/miniconda3/envs/py27/lib/python2.7
PYTHON_PKGS=/Users/klay6683/miniconda3/envs/py27/lib/python2.7/site-packages

rm -f cspice.py cspice_wrap.c cspice_wrap.o

swig -python cspice.i

rm -f __init__.py
mv cspice.py __init__.py

gcc -c `python-config --cflags` cspice_wrap.c -I$PYTHON_INCLUDE \
    -I$PYTHON_PKGS/numpy/core/include -Icspice/src/cspice

rm -f _cspice.so

ld -bundle `python-config --ldflags` -flat_namespace -undefined suppress \
    -o _cspice.so cspice_wrap.o cspice/lib/cspice.a -lm

rm -f cspice_wrap.c cspice_wrap.o
```
Note that I adapted the paths as recommended.
I don't see where here an install into my Python library happens here. 
Hence, I presume, the `import cspice` keeps failing for me.

**Comment by rfrenchseti** [comment]
Hi,

This build process is not supposed to install cspice as an official 
Python package. Instead, you have to either run python from the 
pds-tools directory, or add pds-tools to your PYTHONPATH environment 
variable. Please let me know if you have further problems.

Rob French
rfrench@seti.org
