### ISSUE TITLE
license for pds-tools?

### ISSUE THREAD

**Issue by AndrewAnnex** [SETI/pds-tools#7]
Hey so there were some good ideas revolving around exceptions in the cspyce codebase that has been removed a few commits ago that I want to use in spiceypy. Is there a license for the project that I can list or is the code considered public domain? I think by default it is all rights reserved with github so could the code be relicensed to be free?

**Comment by rfrenchseti** [comment]
cspyce has been moved to its own repo `https://github.com/SETI/pds-cspyce`. It is licensed under Academic Free License ("AFL") v. 3.0.
